### ISSUE TITLE
دریافت پیام کاربر

### ISSUE THREAD

**Issue by mostafaasadi** [toolkito/Python-Gap-SDP-API#1]
<p dir='rtl' align='right'>سلام
مدتی بود خودم درگیر بودم که حداقل برای امکانات پایه یک کلاس بنویسم ولی خب امروز دیدم شما زحمتش را کشیدید و تشکر میکنم :rose: 
</p>
<p dir='rtl' align='right'>
من درباره دریافت پیام ابهام دارم ، در ربات های تلگرامی ما ربات را به حالت idle میبریم و هر پیامی که از سمت کاربری ارسال شود هندلرهای مختلف برای توابع مختلف میفرستند ولی من روند دریافت پیام کاربر را درباره گپ متوجه نمیشم 
اگر توضیح کوتاهی بفرمایید ممنونم
</p>

**Comment by alihesari** [comment]
سلام ساختار گپ هم به صورت تلگرام هست و تفاوت چندانی نداره. نمونه کد زیر رو ببینید بازهم اگر سوالی داشتید بفرمایید:

‍‍‍```
def gap_list(request):
if request.method == 'POST':
       if request.data['type'] == 'text' and request.data['data'] in {'/QuickEvent', '/AdvanceEvent'}:
            gap_api.send_text(
                chat_id,
                data='نوع یادآور را انتخاب کنید.',
                reply_keyboard={
                      'keyboard': [
                          [{'/Cancel': 'انصراف'}]
                      ],
                      'once': True,
                      'selective': False
                  },
                inline_keyboard=[
                      [
                          {'cb_data': '/Meeting', 'text': 'قرارملاقات'},
                          {'cb_data': '/Session', 'text': 'جلسه'},
                          {'cb_data': '/Buying', 'text': 'خرید'}
                      ],
                      [
                          {'cb_data': '/Debt', 'text': 'قسط بانک'},
                          {'cb_data': '/Cheque', 'text': 'موعد چک'},
                          {'cb_data': '/PayRent', 'text': 'موعد اجاره'}
                      ],
                      [
                          {'cb_data': '/Doctor', 'text': 'نوبت پزشک'},
                          {'cb_data': '/Medicine', 'text': 'خوردن دارو'},
                          {'cb_data': '/Visit', 'text': 'عیادت بیمار'}
                      ],
                      [
                          {'cb_data': '/Ceremony', 'text': 'شرکت در مراسم'},
                          {'cb_data': '/Party', 'text': 'مهمانی'},
                          {'cb_data': '/Congratulate', 'text': 'تبریک و تسلیت'},
                      ],
                      [
                          {'cb_data': '/CarInsurance', 'text': 'بیمه ماشین'},
                          {'cb_data': '/Custom', 'text': 'یادآور دلخواه'}
                      ]
                ])
            return Response(data='NewEvent', status=status.HTTP_200_OK)
```

**Comment by mostafaasadi** [comment]
سلام 
ممنون از توضیحاتتون
الان این رکوئست دقیقا چیه ؟ از کجا میاد ؟

**Comment by alihesari** [comment]
@mostafaasadi از طرف سرور گپ
